export const ENV_DB_TYPE_KEY = 'DB_TYPE';
export const ENV_DB_HOST_KEY = 'DB_HOST';
export const ENV_DB_PORT_KEY = 'DB_PORT';
export const ENV_DB_USERNAME_KEY = 'DB_USERNAME';
export const ENV_DB_PASSWORD_KEY = 'DB_PASSWORD';
export const ENV_DB_NAME_KEY = 'DB_NAME';

export const ENV_JWT_SECRET = 'JWT_SECRET';
export const ENV_JWT_TOKEN_EXPIRES_IN = 'JWT_TOKEN_EXPIRES_IN';
export const ENV_JWT_REFRESH_SECRET = 'JWT_REFRESH_SECRET';
export const ENV_JWT_REFRESH_TOKEN_EXPIRES_IN = 'JWT_REFRESH_TOKEN_EXPIRES_IN';

export const ENV_OAUTH_GITHUB_CLIENT_ID = 'OAUTH_GITHUB_CLIENT_ID';
export const ENV_OAUTH_GITHUB_CLIENT_SECRETS = 'OAUTH_GITHUB_CLIENT_SECRETS';
export const ENV_OAUTH_GITHUB_CALLBACK_URL = 'OAUTH_GITHUB_CALLBACK_URL';
